require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ClaroExtractsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ClaroExtract. As you add validations to ClaroExtract, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClaroExtractsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all claro_extracts as @claro_extracts" do
      claro_extract = ClaroExtract.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:claro_extracts)).to eq([claro_extract])
    end
  end

  describe "GET show" do
    it "assigns the requested claro_extract as @claro_extract" do
      claro_extract = ClaroExtract.create! valid_attributes
      get :show, {:id => claro_extract.to_param}, valid_session
      expect(assigns(:claro_extract)).to eq(claro_extract)
    end
  end

  describe "GET new" do
    it "assigns a new claro_extract as @claro_extract" do
      get :new, {}, valid_session
      expect(assigns(:claro_extract)).to be_a_new(ClaroExtract)
    end
  end

  describe "GET edit" do
    it "assigns the requested claro_extract as @claro_extract" do
      claro_extract = ClaroExtract.create! valid_attributes
      get :edit, {:id => claro_extract.to_param}, valid_session
      expect(assigns(:claro_extract)).to eq(claro_extract)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClaroExtract" do
        expect {
          post :create, {:claro_extract => valid_attributes}, valid_session
        }.to change(ClaroExtract, :count).by(1)
      end

      it "assigns a newly created claro_extract as @claro_extract" do
        post :create, {:claro_extract => valid_attributes}, valid_session
        expect(assigns(:claro_extract)).to be_a(ClaroExtract)
        expect(assigns(:claro_extract)).to be_persisted
      end

      it "redirects to the created claro_extract" do
        post :create, {:claro_extract => valid_attributes}, valid_session
        expect(response).to redirect_to(ClaroExtract.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved claro_extract as @claro_extract" do
        post :create, {:claro_extract => invalid_attributes}, valid_session
        expect(assigns(:claro_extract)).to be_a_new(ClaroExtract)
      end

      it "re-renders the 'new' template" do
        post :create, {:claro_extract => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested claro_extract" do
        claro_extract = ClaroExtract.create! valid_attributes
        put :update, {:id => claro_extract.to_param, :claro_extract => new_attributes}, valid_session
        claro_extract.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested claro_extract as @claro_extract" do
        claro_extract = ClaroExtract.create! valid_attributes
        put :update, {:id => claro_extract.to_param, :claro_extract => valid_attributes}, valid_session
        expect(assigns(:claro_extract)).to eq(claro_extract)
      end

      it "redirects to the claro_extract" do
        claro_extract = ClaroExtract.create! valid_attributes
        put :update, {:id => claro_extract.to_param, :claro_extract => valid_attributes}, valid_session
        expect(response).to redirect_to(claro_extract)
      end
    end

    describe "with invalid params" do
      it "assigns the claro_extract as @claro_extract" do
        claro_extract = ClaroExtract.create! valid_attributes
        put :update, {:id => claro_extract.to_param, :claro_extract => invalid_attributes}, valid_session
        expect(assigns(:claro_extract)).to eq(claro_extract)
      end

      it "re-renders the 'edit' template" do
        claro_extract = ClaroExtract.create! valid_attributes
        put :update, {:id => claro_extract.to_param, :claro_extract => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested claro_extract" do
      claro_extract = ClaroExtract.create! valid_attributes
      expect {
        delete :destroy, {:id => claro_extract.to_param}, valid_session
      }.to change(ClaroExtract, :count).by(-1)
    end

    it "redirects to the claro_extracts list" do
      claro_extract = ClaroExtract.create! valid_attributes
      delete :destroy, {:id => claro_extract.to_param}, valid_session
      expect(response).to redirect_to(claro_extracts_url)
    end
  end

end
