require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ClaroManagerByLinesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ClaroManagerByLine. As you add validations to ClaroManagerByLine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClaroManagerByLinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all claro_manager_by_lines as @claro_manager_by_lines" do
      claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:claro_manager_by_lines)).to eq([claro_manager_by_line])
    end
  end

  describe "GET show" do
    it "assigns the requested claro_manager_by_line as @claro_manager_by_line" do
      claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
      get :show, {:id => claro_manager_by_line.to_param}, valid_session
      expect(assigns(:claro_manager_by_line)).to eq(claro_manager_by_line)
    end
  end

  describe "GET new" do
    it "assigns a new claro_manager_by_line as @claro_manager_by_line" do
      get :new, {}, valid_session
      expect(assigns(:claro_manager_by_line)).to be_a_new(ClaroManagerByLine)
    end
  end

  describe "GET edit" do
    it "assigns the requested claro_manager_by_line as @claro_manager_by_line" do
      claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
      get :edit, {:id => claro_manager_by_line.to_param}, valid_session
      expect(assigns(:claro_manager_by_line)).to eq(claro_manager_by_line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClaroManagerByLine" do
        expect {
          post :create, {:claro_manager_by_line => valid_attributes}, valid_session
        }.to change(ClaroManagerByLine, :count).by(1)
      end

      it "assigns a newly created claro_manager_by_line as @claro_manager_by_line" do
        post :create, {:claro_manager_by_line => valid_attributes}, valid_session
        expect(assigns(:claro_manager_by_line)).to be_a(ClaroManagerByLine)
        expect(assigns(:claro_manager_by_line)).to be_persisted
      end

      it "redirects to the created claro_manager_by_line" do
        post :create, {:claro_manager_by_line => valid_attributes}, valid_session
        expect(response).to redirect_to(ClaroManagerByLine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved claro_manager_by_line as @claro_manager_by_line" do
        post :create, {:claro_manager_by_line => invalid_attributes}, valid_session
        expect(assigns(:claro_manager_by_line)).to be_a_new(ClaroManagerByLine)
      end

      it "re-renders the 'new' template" do
        post :create, {:claro_manager_by_line => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested claro_manager_by_line" do
        claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
        put :update, {:id => claro_manager_by_line.to_param, :claro_manager_by_line => new_attributes}, valid_session
        claro_manager_by_line.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested claro_manager_by_line as @claro_manager_by_line" do
        claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
        put :update, {:id => claro_manager_by_line.to_param, :claro_manager_by_line => valid_attributes}, valid_session
        expect(assigns(:claro_manager_by_line)).to eq(claro_manager_by_line)
      end

      it "redirects to the claro_manager_by_line" do
        claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
        put :update, {:id => claro_manager_by_line.to_param, :claro_manager_by_line => valid_attributes}, valid_session
        expect(response).to redirect_to(claro_manager_by_line)
      end
    end

    describe "with invalid params" do
      it "assigns the claro_manager_by_line as @claro_manager_by_line" do
        claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
        put :update, {:id => claro_manager_by_line.to_param, :claro_manager_by_line => invalid_attributes}, valid_session
        expect(assigns(:claro_manager_by_line)).to eq(claro_manager_by_line)
      end

      it "re-renders the 'edit' template" do
        claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
        put :update, {:id => claro_manager_by_line.to_param, :claro_manager_by_line => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested claro_manager_by_line" do
      claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
      expect {
        delete :destroy, {:id => claro_manager_by_line.to_param}, valid_session
      }.to change(ClaroManagerByLine, :count).by(-1)
    end

    it "redirects to the claro_manager_by_lines list" do
      claro_manager_by_line = ClaroManagerByLine.create! valid_attributes
      delete :destroy, {:id => claro_manager_by_line.to_param}, valid_session
      expect(response).to redirect_to(claro_manager_by_lines_url)
    end
  end

end
