require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TypeCompaniesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TypeCompany. As you add validations to TypeCompany, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TypeCompaniesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all type_companies as @type_companies" do
      type_company = TypeCompany.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:type_companies)).to eq([type_company])
    end
  end

  describe "GET show" do
    it "assigns the requested type_company as @type_company" do
      type_company = TypeCompany.create! valid_attributes
      get :show, {:id => type_company.to_param}, valid_session
      expect(assigns(:type_company)).to eq(type_company)
    end
  end

  describe "GET new" do
    it "assigns a new type_company as @type_company" do
      get :new, {}, valid_session
      expect(assigns(:type_company)).to be_a_new(TypeCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested type_company as @type_company" do
      type_company = TypeCompany.create! valid_attributes
      get :edit, {:id => type_company.to_param}, valid_session
      expect(assigns(:type_company)).to eq(type_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TypeCompany" do
        expect {
          post :create, {:type_company => valid_attributes}, valid_session
        }.to change(TypeCompany, :count).by(1)
      end

      it "assigns a newly created type_company as @type_company" do
        post :create, {:type_company => valid_attributes}, valid_session
        expect(assigns(:type_company)).to be_a(TypeCompany)
        expect(assigns(:type_company)).to be_persisted
      end

      it "redirects to the created type_company" do
        post :create, {:type_company => valid_attributes}, valid_session
        expect(response).to redirect_to(TypeCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved type_company as @type_company" do
        post :create, {:type_company => invalid_attributes}, valid_session
        expect(assigns(:type_company)).to be_a_new(TypeCompany)
      end

      it "re-renders the 'new' template" do
        post :create, {:type_company => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested type_company" do
        type_company = TypeCompany.create! valid_attributes
        put :update, {:id => type_company.to_param, :type_company => new_attributes}, valid_session
        type_company.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested type_company as @type_company" do
        type_company = TypeCompany.create! valid_attributes
        put :update, {:id => type_company.to_param, :type_company => valid_attributes}, valid_session
        expect(assigns(:type_company)).to eq(type_company)
      end

      it "redirects to the type_company" do
        type_company = TypeCompany.create! valid_attributes
        put :update, {:id => type_company.to_param, :type_company => valid_attributes}, valid_session
        expect(response).to redirect_to(type_company)
      end
    end

    describe "with invalid params" do
      it "assigns the type_company as @type_company" do
        type_company = TypeCompany.create! valid_attributes
        put :update, {:id => type_company.to_param, :type_company => invalid_attributes}, valid_session
        expect(assigns(:type_company)).to eq(type_company)
      end

      it "re-renders the 'edit' template" do
        type_company = TypeCompany.create! valid_attributes
        put :update, {:id => type_company.to_param, :type_company => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested type_company" do
      type_company = TypeCompany.create! valid_attributes
      expect {
        delete :destroy, {:id => type_company.to_param}, valid_session
      }.to change(TypeCompany, :count).by(-1)
    end

    it "redirects to the type_companies list" do
      type_company = TypeCompany.create! valid_attributes
      delete :destroy, {:id => type_company.to_param}, valid_session
      expect(response).to redirect_to(type_companies_url)
    end
  end

end
